# Generated by Django 5.0 on 2023-12-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, unique=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Retired', 'Retired'), ('Internship', 'Internship')], max_length=20, null=True)),
                ('sub_unit', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
